# Generated by Django 3.1.3 on 2020-11-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0002_auto_20201107_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='media', verbose_name='Картинка')),
            ],
        ),
        migrations.RemoveField(
            model_name='new',
            name='image',
        ),
    ]
