# Generated by Django 3.1.3 on 2020-11-08 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0003_auto_20201108_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='newimage',
            name='new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='museum.new'),
        ),
    ]
