# Generated by Django 3.1.3 on 2020-11-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0004_newimage_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True, verbose_name='Описание События')),
                ('dateEvent', models.DateField(verbose_name='Дата События')),
            ],
        ),
    ]
