# Generated by Django 3.1.3 on 2020-11-08 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0007_auto_20201109_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='date',
            field=models.DateField(verbose_name='Дата Публикации'),
        ),
    ]
