# Generated by Django 3.1.3 on 2020-11-17 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0009_auto_20201111_0206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254)),
                ('text', models.TextField(verbose_name='Текст')),
                ('check_on_number', models.BooleanField(verbose_name='Связаться по телефону')),
                ('check_on_email', models.BooleanField(verbose_name='Связаться по Email')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
