# Generated by Django 3.1.3 on 2020-11-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0010_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Организация')),
                ('phone', models.IntegerField(verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254)),
                ('count_users', models.IntegerField(verbose_name='Количество Участников')),
                ('date_application', models.DateField(verbose_name='Дата экскурсии')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.RemoveField(
            model_name='review',
            name='check_on_email',
        ),
        migrations.RemoveField(
            model_name='review',
            name='check_on_number',
        ),
        migrations.RemoveField(
            model_name='review',
            name='phone',
        ),
    ]
