# Generated by Django 3.1.3 on 2020-11-18 19:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0011_auto_20201118_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date_review',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата отзыва'),
            preserve_default=False,
        ),
    ]
