# Generated by Django 3.1.3 on 2020-11-19 15:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0012_review_date_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Описание Новости'),
        ),
    ]
