# Generated by Django 3.1.3 on 2020-11-19 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0013_auto_20201119_1818'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalendarEvent',
        ),
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='newimage',
            options={'verbose_name': 'Картинки для новости', 'verbose_name_plural': 'Картинки для новости'},
        ),
        migrations.AlterField(
            model_name='new',
            name='title',
            field=models.TextField(verbose_name='Название новости'),
        ),
    ]
