# Generated by Django 3.1.3 on 2020-11-20 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0014_auto_20201120_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newimage',
            name='new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='museum.new', verbose_name='Новость'),
        ),
    ]
