# Generated by Django 3.1.3 on 2020-11-23 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0015_auto_20201120_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watermark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('image', models.ImageField(upload_to='watermarks', verbose_name='image')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='is active')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='newimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/%Y/%m/%d/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(max_length=10000, verbose_name='Текст'),
        ),
    ]
