# Generated by Django 3.1.3 on 2020-11-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0016_auto_20201123_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(max_length=10000, verbose_name='Текст'),
        ),
    ]
