# Generated by Django 3.1.3 on 2020-11-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0019_auto_20201125_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=models.DateTimeField()),
        ),
    ]
