# Generated by Django 3.1.3 on 2020-11-24 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0020_auto_20201125_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
    ]
