# Generated by Django 3.1.3 on 2020-11-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0021_remove_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='somthing'),
        ),
    ]
