# Generated by Django 3.1.3 on 2020-11-24 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0022_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(),
        ),
    ]
