# Generated by Django 3.1.3 on 2020-12-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0023_auto_20201125_0241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleFIO', models.TextField(verbose_name='Имя Фамилия Отчество почётного гостя')),
                ('imageGuest', models.ImageField(upload_to='media/%Guest/', verbose_name='Фото почётного гостя')),
                ('descriptionGuest', models.ImageField(upload_to='media/%Guest/%review/', verbose_name='Отзыв гостя')),
                ('dateReview', models.DateField(verbose_name='Дата Отзыва')),
            ],
            options={
                'verbose_name': 'Почётный гость',
                'verbose_name_plural': 'Почётные гости',
            },
        ),
    ]
