# Generated by Django 3.1.3 on 2020-12-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0024_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='descriptionGuest',
            field=models.ImageField(upload_to='media/%Y/%m/%d/', verbose_name='Отзыв гостя'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='imageGuest',
            field=models.ImageField(upload_to='media/%Y/%m/%d/', verbose_name='Фото почётного гостя'),
        ),
    ]
