# Generated by Django 3.1.3 on 2020-12-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0028_auto_20201208_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='phone',
            field=models.CharField(default=375, max_length=20, verbose_name='контактный телефон'),
        ),
    ]
