# Generated by Django 3.1.3 on 2020-12-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0030_auto_20201208_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='phone',
            field=models.IntegerField(default='', verbose_name='контактный телефон'),
        ),
    ]
