# Generated by Django 3.1.3 on 2020-12-08 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0031_auto_20201208_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='countUser',
            new_name='userscount',
        ),
    ]
