# Generated by Django 3.1.3 on 2020-12-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0032_auto_20201208_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='FIO',
            field=models.TextField(default='0', verbose_name='ФИО ответственного'),
        ),
    ]
