# Generated by Django 3.1.3 on 2020-12-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0033_auto_20201208_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='FIO',
            field=models.TextField(default='', verbose_name='ФИО ответственного'),
        ),
        migrations.AlterField(
            model_name='event',
            name='userscount',
            field=models.IntegerField(verbose_name='Количество участников'),
        ),
    ]
